theme: jekyll-theme-minimal
title: Il mio Portfolio
description: "Hi 👋, I'm Luca Galli
A passionate Data Scientist and Computer Scientist

<br>

- 🍕 I was born in May 2000, near Milan (Italy)
- 📑 Level C1 English (Cambridge Certificate)
- 🎓 I have a Bachelor's Degree in Computer Science
- 🌱 I have a Master's Degree in Data Science
- 👉 You can check out some of my University Projects on this website
- 📫 You can contact me on my email for any need!"
logo: https://github.com/LucaGalliProjects/LucaGalliProjects.github.io/blob/main/fotoCVLucaGalli.png
