theme: jekyll-theme-minimal
title: Il mio Portfolio
logo: /fotoCVLucaGalli.png
description: |
  A passionate Data Scientist and Computer Scientist 🍕 Milano (Italy).
  <br><br>
  <strong>Connect:</strong><br>
  <a href="https://linkedin.com/in/luca-ga"><img src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" width="30"></a>
  <br><br>
  <strong>Top Skills:</strong><br>
  <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg" width="25">
  <img src="https://raw.githubusercontent.com/devicons/devicon/2ae2a900d2f041da66e950e4d48052658d850630/icons/pandas/pandas-original.svg" width="25">
  <img src="https://www.vectorlogo.zone/logos/tensorflow/tensorflow-icon.svg" width="25">
